version: "3"

services:
  web:
    build: .
#    container_name: oc-lettings
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./:/app # nom local : nom dans conteneur
    depends_on:
      - db

  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./data/db:/root/db
    environment:
      - SQLITE3_DB=oc-lettings-site.sqlite3
